export type AUTH_ERROR_TYPE = "AUTH_ERROR";
export const AUTH_ERROR: AUTH_ERROR_TYPE = "AUTH_ERROR";

export type AUTH_SUCCESS_TYPE = "AUTH_SUCCESS";
export const AUTH_SUCCESS: AUTH_SUCCESS_TYPE = "AUTH_SUCCESS";

export type AUTH_LOADING_TYPE = "AUTH_LOADING";
export const AUTH_LOADING: AUTH_LOADING_TYPE = "AUTH_LOADING";

export type CHANGE_VIEW_TYPE = "CHANGE_VIEW";
export const CHANGE_VIEW: CHANGE_VIEW_TYPE = "CHANGE_VIEW";

export type CHANGE_CAMS_STATE_TYPE = "CHANGE_CAMS_STATE";
export const CHANGE_CAMS_STATE: CHANGE_CAMS_STATE_TYPE = "CHANGE_CAMS_STATE";
